#!/bin/bash

# Copyright 2014 Twitter, Inc.
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
# http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.

# Launch Raggiana with preloaded stats
# Author: michael.zalimeni@bronto.com

# Copy Raggiana into tmp
cp -r "./raggiana" "./tmp/"
cd "./tmp/"

# Write to placeholder in stats/index.html
sed '/_DATA_PLACEHOLDER/{rparrot-server-stats.log
d
}' ../raggiana/index.html > ./raggiana/index.html

# Open Raggiana
open "./raggiana/index.html"
